/**
 * @module exportUtils
 * @description Browser-only utilities for generating shell / batch copy scripts
 *              and triggering file downloads via the Blob API.
 *
 * IMPORTANT: This module is BROWSER-ONLY.
 * It uses document.createElement, URL.createObjectURL, and Blob.
 * Do not import it from a server component, API route, or Node.js script.
 *
 * Two script formats are supported:
 *   • Bash (.sh)  — Mac and Linux. Uses 'set -euo pipefail', 'mkdir -p', 'cp'
 *   • Batch (.bat) — Windows. Uses 'copy /Y', label-based branches, subroutines
 *
 * Generated scripts are self-contained and reviewed-friendly:
 *   each file gets a labelled copy_file / :copy_file call so the user can
 *   read and verify the script before running it.
 */

import type { ParsedTrack } from './types';

// ─────────────────────────────────────────────────────────────────────────────
// BASH SCRIPT GENERATOR (Mac / Linux)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generate a Bash shell script (.sh) that copies the playlist audio files
 * to a destination directory when executed on Mac or Linux.
 *
 * Generated script features
 * ─────────────────────────
 *   • Strict mode (`set -euo pipefail`) — fails fast on unexpected errors
 *   • `mkdir -p` — creates the destination recursively without error if it exists
 *   • Per-file `[[ -f … ]]` guard — skips missing files with a warning instead of aborting
 *   • Running counters: COPIED, SKIPPED, FAILED printed at the end
 *   • Idempotent: re-running overwrites existing files (standard `cp` behaviour)
 *   • Security review header encouraging the user to read it first
 *
 * @param {ParsedTrack[]} tracks      - Parsed playlist tracks to copy
 * @param {string}        destination - Absolute path to the destination directory
 * @returns {string} Complete bash script as a multi-line string
 */
export function generateBashScript(tracks: ParsedTrack[], destination: string): string {
  const escapedDest = shellEscape(destination);
  const generatedAt = new Date().toLocaleString();

  // Collect unique playlist names (insertion order = order first seen)
  const playlistNames = [...new Set(tracks.map((t) => t.playlistName))];

  // ── mkdir -p for every playlist subfolder ──────────────────────────────────
  const mkdirLines = playlistNames
    .map((name) => `mkdir -p ${shellEscape(destination + '/' + name)}`)
    .join('\n');

  // ── Folder structure comment block ─────────────────────────────────────────
  const folderStructure = playlistNames
    .map((n) => {
      const count = tracks.filter((t) => t.playlistName === n).length;
      return `#     ${n}/   (${count} track${count !== 1 ? 's' : ''})`;
    })
    .join('\n');

  // ── One copy_file call per track ───────────────────────────────────────────
  const copyLines = tracks
    .map((t) => `  copy_file ${shellEscape(t.sourcePath)} ${shellEscape(t.playlistName)}`)
    .join('\n');

  return `#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Music Export Script  (Mac / Linux)
# ─────────────────────────────────────────────────────────────────────────────
# Generated by : Music Export Tool — sysya-wiki
# Generated on : ${generatedAt}
# Total tracks : ${tracks.length}
# Playlists    : ${playlistNames.length}
#
# DESTINATION FOLDER STRUCTURE
#   ${destination}/
${folderStructure}
#
# USAGE
#   chmod +x export-music.sh
#   ./export-music.sh
#
# VERIFICATION
#   Each file is verified immediately after copying (inline -f check).
#   The script exits with code 1 if any file failed or could not be verified.
#
# SECURITY NOTE
#   Review this script before running it.
#   Do not execute scripts from untrusted sources.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ─── Configuration ───────────────────────────────────────────────────────────────
readonly DEST=${escapedDest}

# ─── Counters ────────────────────────────────────────────────────────────────────
COPIED=0
SKIPPED=0
FAILED=0

# ─── Helper: copy one file into its playlist subfolder, then verify ───────────────
#
# Arguments:
#   \$1  src           — absolute source path
#   \$2  playlist_dir  — playlist subfolder name under DEST
#
# Verification:
#   After cp exits 0, we do a second [[ -f dest_file ]] check.
#   This catches rare edge cases (NFS flush lag, FAT32 write buffering)
#   where cp reports success but the file is not yet visible.
#
copy_file() {
  local src="\$1"
  local playlist_dir="\$2"
  local filename
  filename="$(basename "\$src")"
  local dest_dir="\$DEST/\$playlist_dir"
  local dest_file="\$dest_dir/\$filename"

  # Guard 1: source must exist
  if [[ ! -f "\$src" ]]; then
    echo "  \u26a0  SKIPPED  (not found): [\$playlist_dir] \$filename"
    (( SKIPPED++ )) || true
    return 0
  fi

  # Copy the file
  if cp -- "\$src" "\$dest_file"; then
    # Guard 2 (verification): confirm the file landed at the destination
    if [[ -f "\$dest_file" ]]; then
      echo "  \u2713  Copied:  [\$playlist_dir] \$filename"
      (( COPIED++ )) || true
    else
      echo "  \u2717  UNVERIFIED — missing after copy: [\$playlist_dir] \$filename"
      (( FAILED++ )) || true
    fi
  else
    echo "  \u2717  FAILED:  [\$playlist_dir] \$filename"
    (( FAILED++ )) || true
  fi
}

# ─── Create root destination + one subfolder per playlist ──────────────────────
echo ""
echo "Creating directories..."
mkdir -p "$DEST"
${mkdirLines}
echo ""
echo "Exporting ${tracks.length} track(s) across ${playlistNames.length} playlist(s)..."
echo ""

# ─── Copy files (one call per track) ───────────────────────────────────────────────
${copyLines}

# ─── Final summary ────────────────────────────────────────────────────────────────
echo ""
echo "────────────────────────────────────────────"
echo "Done."
echo "  Copied & verified  : \$COPIED"
echo "  Skipped (not found): \$SKIPPED"
echo "  Failed             : \$FAILED"
echo ""

# Exit code 1 if any file failed — easy to detect in CI or a parent script.
# Skipped (not-found) files are intentionally NOT treated as failures.
if (( FAILED > 0 )); then
  echo "\u26a0  Exiting with code 1 — \$FAILED file(s) did not copy correctly."
  exit 1
fi

echo "\u2713  All \$COPIED file(s) copied and verified. Zero failures."
exit 0
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// BATCH SCRIPT GENERATOR (Windows)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generate a Windows Batch script (.bat) that copies the playlist audio files
 * to a destination directory when executed on Windows.
 *
 * Uses the built-in COPY command with an exact destination filename. This avoids
 * XCOPY's interactive file-or-directory prompt and works in a plain cmd.exe.
 *
 * @param {ParsedTrack[]} tracks      - Parsed playlist tracks to copy
 * @param {string}        destination - Absolute Windows path (e.g. D:\\Export)
 * @returns {string} Complete .bat script as a multi-line string
 */
export function generateBatchScript(tracks: ParsedTrack[], destination: string): string {
  const normalizedDestination = normalizeBatchPath(destination);
  const generatedAt = new Date().toLocaleString();
  const manifest = JSON.stringify({
    destination: normalizedDestination,
    tracks: tracks.map((track) => ({
      sourcePath: normalizeBatchPath(track.sourcePath),
      playlistName: track.playlistName,
    })),
  });
  const encodedBootstrap = encodePowerShellCommand(POWERSHELL_BATCH_BOOTSTRAP);

  const script = `@echo off
REM ─────────────────────────────────────────────────────────────────────────────
REM Music Export Script  (Windows)
REM ─────────────────────────────────────────────────────────────────────────────
REM Generated by : Music Export Tool -- sysya-wiki
REM Generated on : ${generatedAt}
REM Total tracks : ${tracks.length}
REM
REM USAGE
REM   Double-click this .bat file or run from the Command Prompt
REM
REM Requires Windows PowerShell 5.1, included with Windows 10.
REM ─────────────────────────────────────────────────────────────────────────────
setlocal DisableDelayedExpansion
set "MUSIC_EXPORT_SCRIPT=%~f0"
powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -EncodedCommand ${encodedBootstrap}
set "MUSIC_EXPORT_EXIT=%ERRORLEVEL%"
endlocal & exit /b %MUSIC_EXPORT_EXIT%
__MUSIC_EXPORT_RUNNER__
${POWERSHELL_BATCH_RUNNER}
__MUSIC_EXPORT_MANIFEST__
${manifest}
`;

  // cmd.exe accepts LF in many cases, but CRLF is the native and most reliable
  // batch-file line ending. Normalize after interpolating generated sections.
  return script.replace(/\r?\n/g, '\r\n');
}

const POWERSHELL_BATCH_BOOTSTRAP = `$content = [IO.File]::ReadAllText($env:MUSIC_EXPORT_SCRIPT, [Text.UTF8Encoding]::new($false))
$runnerMarker = "__MUSIC_EXPORT_RUNNER__\`r\`n"
$manifestMarker = "__MUSIC_EXPORT_MANIFEST__\`r\`n"
$runnerStart = $content.IndexOf($runnerMarker)
$manifestStart = $content.LastIndexOf($manifestMarker)
if ($runnerStart -lt 0 -or $manifestStart -le $runnerStart) { throw 'Embedded music export runner was not found.' }
$runnerStart += $runnerMarker.Length
$runner = $content.Substring($runnerStart, $manifestStart - $runnerStart)
& ([ScriptBlock]::Create($runner))`;

const POWERSHELL_BATCH_RUNNER = `$ErrorActionPreference = 'Stop'
$content = [IO.File]::ReadAllText($env:MUSIC_EXPORT_SCRIPT, [Text.UTF8Encoding]::new($false))
$marker = "__MUSIC_EXPORT_MANIFEST__\`r\`n"
$markerIndex = $content.LastIndexOf($marker)
if ($markerIndex -lt 0) { throw 'Embedded music export manifest was not found.' }
$job = $content.Substring($markerIndex + $marker.Length).Trim() | ConvertFrom-Json
$copied = 0
$missing = 0
$failed = 0
$trackNumber = 0
Write-Host ''
Write-Host ('Destination: ' + $job.destination)
Write-Host ('Tracks: ' + $job.tracks.Count)
Write-Host ''
if ($job.destination.Length -lt 3 -or $job.destination[1] -ne ':' -or $job.destination[2] -ne '\\') {
  throw ('Destination must be an absolute Windows path: ' + $job.destination)
}
$sampleCount = [Math]::Min(50, [int]$job.tracks.Count)
$sampleTracks = @(for ($sampleIndex = 0; $sampleIndex -lt $sampleCount; $sampleIndex++) {
  $job.tracks[[Math]::Floor($sampleIndex * $job.tracks.Count / $sampleCount)]
})
$configuredMatches = @($sampleTracks | Where-Object { Test-Path -LiteralPath $_.sourcePath -PathType Leaf }).Count
if ($sampleCount -gt 0 -and $configuredMatches -eq 0) {
  $bestDrive = $null
  $bestMatches = 0
  foreach ($drive in @(Get-PSDrive -PSProvider FileSystem)) {
    $driveMatches = 0
    foreach ($sampleTrack in $sampleTracks) {
      if ($sampleTrack.sourcePath.Length -ge 3 -and $sampleTrack.sourcePath[1] -eq ':' -and $sampleTrack.sourcePath[2] -eq '\\') {
        $candidatePath = Join-Path -Path $drive.Root -ChildPath $sampleTrack.sourcePath.Substring(3)
        if (Test-Path -LiteralPath $candidatePath -PathType Leaf) { $driveMatches++ }
      }
    }
    if ($driveMatches -gt $bestMatches) { $bestDrive = $drive.Root; $bestMatches = $driveMatches }
  }
  Write-Host ('ERROR: None of ' + $sampleCount + ' sampled source files exist at the configured paths.')
  if ($bestMatches -gt 0) {
    Write-Host ('Likely source drive: ' + $bestDrive + ' (' + $bestMatches + ' of ' + $sampleCount + ' samples found)')
    Write-Host ('Regenerate the script using source drive letter ' + $bestDrive.Substring(0, 1) + '.')
  } else {
    Write-Host 'No mounted drive matched the sampled playlist paths.'
  }
  exit 1
}
if (-not (Test-Path -LiteralPath $job.destination -PathType Container)) {
  New-Item -ItemType Directory -Path $job.destination -Force | Out-Null
}
foreach ($track in $job.tracks) {
  $trackNumber++
  if (-not (Test-Path -LiteralPath $track.sourcePath -PathType Leaf)) {
    Write-Host ('- Track ' + $trackNumber + ' source file not found:')
    Write-Host $track.sourcePath
    $missing++
    continue
  }
  try {
    $destinationDirectory = Join-Path -Path $job.destination -ChildPath $track.playlistName
    New-Item -ItemType Directory -Path $destinationDirectory -Force | Out-Null
    $destinationFile = Join-Path -Path $destinationDirectory -ChildPath ([IO.Path]::GetFileName($track.sourcePath))
    Copy-Item -LiteralPath $track.sourcePath -Destination $destinationFile -Force
    if (-not (Test-Path -LiteralPath $destinationFile -PathType Leaf)) { throw 'Destination verification failed.' }
    Write-Host ('+ Track ' + $trackNumber + ' copied and verified.')
    $copied++
  } catch {
    Write-Host ('x Track ' + $trackNumber + ' failed: ' + $_.Exception.Message)
    Write-Host $track.sourcePath
    $failed++
  }
}
Write-Host ''
Write-Host '------------------------------------------'
Write-Host ('Copied and verified: ' + $copied)
Write-Host ('Missing: ' + $missing)
Write-Host ('Failed: ' + $failed)
if ($missing -gt 0 -or $failed -gt 0) { exit 1 }
exit 0`;

// ─────────────────────────────────────────────────────────────────────────────
// BROWSER DOWNLOAD TRIGGER
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Trigger a browser file download using a temporary Blob URL.
 *
 * How it works:
 *   1. Create a Blob from the string content
 *   2. Generate a temporary object URL pointing at that Blob
 *   3. Programmatically click a synthetic <a> element with the 'download' attribute
 *   4. Immediately revoke the object URL to free memory
 *
 * The anchor must be attached to the DOM briefly for Firefox compatibility.
 *
 * @param {string} content  - The file content as a string
 * @param {string} filename - Suggested name for the downloaded file (e.g. "export.sh")
 * @param {string} mimeType - MIME type for the Blob (e.g. "text/x-shellscript")
 */
export function triggerDownload(
  content: string,
  filename: string,
  mimeType: string,
): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);

  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.style.display = 'none';

  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);

  // Free the temporary URL immediately — the download is already queued
  URL.revokeObjectURL(url);
}

/**
 * Build the suggested download filename for a script, including today's date.
 *
 * @param {'unix' | 'windows'} os - Target operating system
 * @returns {string} e.g. "export-music-2026-07-29.sh" or "export-music-2026-07-29.bat"
 *
 * @example
 *   getScriptFilename('unix')    // → "export-music-2026-07-29.sh"
 *   getScriptFilename('windows') // → "export-music-2026-07-29.bat"
 */
export function getScriptFilename(os: 'unix' | 'windows'): string {
  const date = new Date().toISOString().split('T')[0]; // "YYYY-MM-DD"
  const ext = os === 'unix' ? 'sh' : 'bat';
  return `export-music-${date}.${ext}`;
}

// ─────────────────────────────────────────────────────────────────────────────
// INTERNAL HELPERS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Escape a string for safe embedding in a bash single-quoted context.
 *
 * Bash single-quoted strings are literal — the only character that needs
 * special handling is a literal single-quote, which ends the current
 * single-quoted string, inserts an escaped single-quote, then reopens it.
 *
 * @example
 *   shellEscape('/path/with spaces/file.mp3') // → "'/path/with spaces/file.mp3'"
 *   shellEscape("/it's/here.mp3")             // → "'/it'\\''s/here.mp3'"
 *
 * @param {string} value - The raw value to escape
 * @returns {string} A bash-safe single-quoted representation
 */
function shellEscape(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

/** Convert slash-separated playlist paths to native Windows separators. */
function normalizeBatchPath(value: string): string {
  const normalized = value.replace(/\//g, '\\');
  return /^[A-Za-z]:$/.test(normalized) ? `${normalized}\\` : normalized;
}

/** PowerShell's -EncodedCommand expects the command as Base64-encoded UTF-16LE. */
function encodePowerShellCommand(command: string): string {
  let binary = '';
  for (let index = 0; index < command.length; index++) {
    const codeUnit = command.charCodeAt(index);
    binary += String.fromCharCode(codeUnit & 0xff, codeUnit >>> 8);
  }
  return btoa(binary);
}
